// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_api_arcanoid_su4ka.DatabaseContextblinept;

#nullable disable

namespace Web_api_arcanoid_su4ka.Migrations
{
    [DbContext(typeof(DatabaseContextsu4ka))]
    partial class DatabaseContextsu4kaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_api_arcanoid_su4ka.Model.Skinmodel", b =>
                {
                    b.Property<int>("ID_Skin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Skin"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("name_ball")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Skin");

                    b.ToTable("Skinmodels");
                });

            modelBuilder.Entity("Web_api_arcanoid_su4ka.Model.UserSkinSvaz", b =>
                {
                    b.Property<int>("ID_Svaz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Svaz"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Skind_id")
                        .HasColumnType("int");

                    b.Property<string>("User_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Svaz");

                    b.ToTable("Userskinmodel");
                });

            modelBuilder.Entity("Web_api_arcanoid_su4ka.Model.Usermodel", b =>
                {
                    b.Property<int>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_user"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("ID_Skin_user")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_user");

                    b.ToTable("Usermodels");
                });
#pragma warning restore 612, 618
        }
    }
}
